const T={id:{app:"Catatan Keuangan NTD",hello:"Semua tersimpan di perangkat ✨",totalBalance:"Total Saldo",offline:"100% Offline",accounts:"Akun & Saldo",income:"Pemasukan",expense:"Pengeluaran",transfer:"Transfer",summary:"Ringkasan Bulan Ini",budget:"Budget Bulanan",used:"Terpakai",chart:"Grafik Pengeluaran",saving:"Target Tabungan",calendar:"Kalender Transaksi",activity:"Transaksi Terbaru",clear:"Hapus",empty:"Belum ada transaksi",home:"Beranda",add:"Tambah",settings:"Pengaturan",amount:"Jumlah",category:"Kategori",account:"Akun",date:"Tanggal",note:"Catatan",save:"Simpan",language:"Bahasa",currency:"Mata Uang",currencyTip:"Mata uang aplikasi: New Taiwan Dollar (NTD). Tidak ada konversi kurs.",simpleBudget:"Batas Budget",simpleGoal:"Target Tabungan",accountPlaceholder:"Contoh: BCA, GoPay, Kas",backupInvalid:"File backup tidak valid.",backup:"Data & Backup",export:"Backup Data",import:"Pulihkan Data",backupNote:"Backup tersimpan sebagai file di perangkatmu. Tidak menggunakan internet.",newAccount:"Tambah Akun",accountType:"Jenis Akun",accountName:"Nama Akun",opening:"Saldo Awal",from:"Dari",to:"Ke",bank:"Bank",ewallet:"E-Wallet",cash:"Cash",ic:["Gaji","Bonus","Bisnis","Hadiah","Lainnya"],ec:["Makanan","Transportasi","Belanja","Tagihan","Hiburan","Kesehatan","Lainnya"]},zh:{app:"私人記帳",hello:"所有資料都儲存在裝置中 ✨",totalBalance:"總餘額",offline:"100% 離線",accounts:"帳戶與餘額",income:"收入",expense:"支出",transfer:"轉帳",summary:"本月摘要",budget:"每月預算",used:"已使用",chart:"支出圖表",saving:"儲蓄目標",calendar:"交易日曆",activity:"最近交易",clear:"刪除",empty:"目前沒有交易",home:"首頁",add:"新增",settings:"設定",amount:"金額",category:"分類",account:"帳戶",date:"日期",note:"備註",save:"儲存",language:"語言",currency:"貨幣",currencyTip:"此應用程式固定使用新臺幣（NTD），不進行匯率轉換。",simpleBudget:"預算上限",simpleGoal:"儲蓄目標",accountPlaceholder:"例如：銀行、電子錢包、現金",backupInvalid:"備份檔案無效。",backup:"資料與備份",export:"備份資料",import:"還原資料",backupNote:"備份為裝置上的檔案，不需要網路。",newAccount:"新增帳戶",accountType:"帳戶類型",accountName:"帳戶名稱",opening:"初始餘額",from:"轉出",to:"轉入",bank:"銀行",ewallet:"電子錢包",cash:"現金",ic:["薪資","獎金","生意","禮物","其他"],ec:["飲食","交通","購物","帳單","娛樂","醫療","其他"]}};
const C={NTD:{s:"NT$",loc:"zh-TW"}};
let S=JSON.parse(localStorage.getItem("financeOfflineNTD")||"null")||{lang:"id",cur:"NTD",accounts:[{id:"cash",type:"cash",name:"Cash",opening:0}],tx:[],budget:0,goal:0,goalName:"Tabungan"},type="in";
const $=s=>document.querySelector(s),tr=k=>T[S.lang][k],today=()=>new Date().toISOString().slice(0,10);
function money(n){return C[S.cur].s+" "+new Intl.NumberFormat(C[S.cur].loc,{maximumFractionDigits:2}).format(n)}
function save(){S.cur="NTD";localStorage.setItem("financeOfflineNTD",JSON.stringify(S))}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function icon(a){return a.type=="bank"?"🏦":a.type=="ewallet"?"📱":"💵"}
function acctBalance(id){let a=S.accounts.find(x=>x.id==id);let n=a?.opening||0;S.tx.forEach(x=>{if(x.type=="in"&&x.accountId==id)n+=x.amount;if(x.type=="out"&&x.accountId==id)n-=x.amount;if(x.type=="transfer"){if(x.from==id)n-=x.amount;if(x.to==id)n+=x.amount}});return n}
function fillAccountTypes(){
  $("#accountType").innerHTML=[
    ["bank","🏦 "+tr("bank")],
    ["ewallet","📱 "+tr("ewallet")],
    ["cash","💵 "+tr("cash")]
  ].map(x=>`<option value="${x[0]}">${x[1]}</option>`).join("");
  $("#accountName").placeholder=tr("accountPlaceholder");
}
function render(){document.querySelectorAll("[data-i]").forEach(e=>e.textContent=tr(e.dataset.i));$("#badge").textContent="NTD";$("#lang").value=S.lang;let total=S.accounts.reduce((a,x)=>a+acctBalance(x.id),0),now=new Date(),y=now.getFullYear(),m=now.getMonth(),arr=S.tx.filter(x=>{let d=new Date(x.date);return d.getFullYear()==y&&d.getMonth()==m}),inc=arr.filter(x=>x.type=="in").reduce((s,x)=>s+x.amount,0),out=arr.filter(x=>x.type=="out").reduce((s,x)=>s+x.amount,0);$("#balance").textContent=money(total);$("#inc").textContent=money(inc);$("#exp").textContent=money(out);$("#month").textContent=now.toLocaleDateString(S.lang=="zh"?"zh-TW":"zh-TW",{month:"long",year:"numeric"});$("#budgetText").textContent=money(out)+" / "+money(S.budget);$("#bar").style.width=S.budget?Math.min(100,out/S.budget*100)+"%":"0%";let allin=S.tx.filter(x=>x.type=="in").reduce((s,x)=>s+x.amount,0);$("#goalName").textContent=S.goalName;$("#goalText").textContent=money(allin)+" / "+money(S.goal);$("#goalbar").style.width=S.goal?Math.min(100,allin/S.goal*100)+"%":"0%";drawAccounts();drawChart(arr);drawCal(y,m);drawList();fillAccounts();fillAccountTypes()}
function drawAccounts(){let box=$("#accountsList");box.innerHTML=S.accounts.map(a=>`<div class="accountCard"><div class="accountTop"><div class="accountIcon">${icon(a)}</div><div class="accountName">${esc(a.name)}</div></div><div class="accountBalance">${money(acctBalance(a.id))}</div><div class="accountType">${tr(a.type=="bank"?"bank":a.type=="ewallet"?"ewallet":"cash")}</div></div>`).join("")}
function fillAccounts(){let opts=S.accounts.map(a=>`<option value="${a.id}">${icon(a)} ${esc(a.name)} — ${money(acctBalance(a.id))}</option>`).join("");$("#account").innerHTML=opts;$("#fromAccount").innerHTML=opts;$("#toAccount").innerHTML=opts}
function drawChart(arr){let ds=Array(7).fill(0);arr.filter(x=>x.type=="out").forEach(x=>{let d=new Date(x.date).getDate();ds[Math.min(6,Math.floor((d-1)/5))]+=x.amount});let max=Math.max(...ds,1);$("#bars").innerHTML=ds.map(v=>`<i class="baritem" style="height:${Math.max(4,v/max*100)}%"></i>`).join("")}
function drawCal(y,m){let first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),names=S.lang=="zh"?["日","一","二","三","四","五","六"]:["S","M","T","W","T","F","S"],out=names.map(x=>`<div class="day head">${x}</div>`).join("");let has=new Set(S.tx.filter(x=>{let d=new Date(x.date);return d.getFullYear()==y&&d.getMonth()==m}).map(x=>new Date(x.date).getDate()));for(let i=0;i<first;i++)out+="<div></div>";for(let d=1;d<=days;d++){let cls="day "+(has.has(d)?"has ":"")+(d==new Date().getDate()?"today":"");out+=`<div class="${cls}">${d}</div>`}$("#calendar").innerHTML=out;$("#calTitle").textContent=new Date(y,m).toLocaleDateString(S.lang=="zh"?"zh-TW":"zh-TW",{month:"long"})}
function drawList(){$("#empty").style.display=S.tx.length?"none":"block";$("#list").innerHTML=[...S.tx].reverse().slice(0,15).map(x=>{let d=new Date(x.date).toLocaleDateString(S.lang=="zh"?"zh-TW":"zh-TW",{day:"2-digit",month:"short"});if(x.type=="transfer")return `<div class="tx"><div class="txicon">⇄</div><div class="txmain"><div class="txcat">${tr("transfer")}</div><div class="txdate">${d} · ${esc(name(x.from))} → ${esc(name(x.to))}</div></div><div class="txamt"> ${money(x.amount)}</div></div>`;return `<div class="tx"><div class="txicon">${x.type=="in"?"💰":"🛍️"}</div><div class="txmain"><div class="txcat">${esc(x.cat)}</div><div class="txdate">${d} · ${esc(name(x.accountId))}${x.note?" · "+esc(x.note):""}</div></div><div class="txamt ${x.type=="in"?"plus":"minus"}">${x.type=="in"?"+":"−"} ${money(x.amount)}</div></div>`}).join("")}
function name(id){return S.accounts.find(a=>a.id==id)?.name||"-"}
function openAdd(k){type=k;$("#modalTitle").textContent=tr(k=="in"?"income":"expense");$("#cat").innerHTML=(k=="in"?T[S.lang].ic:T[S.lang].ec).map(x=>`<option>${x}</option>`).join("");$("#amount").value="";$("#date").value=today();$("#note").value="";fillAccounts();$("#modal").classList.remove("hidden")}
$("#income").onclick=()=>openAdd("in");$("#expense").onclick=()=>openAdd("out");$("#add").onclick=()=>openAdd("out");$("#transfer").onclick=()=>{$("#transferDate").value=today();fillAccounts();$("#transferModal").classList.remove("hidden")};
$("#close").onclick=()=>$("#modal").classList.add("hidden");$("#closeTransfer").onclick=()=>$("#transferModal").classList.add("hidden");
$("#settings").onclick=()=>$("#setmodal").classList.remove("hidden");$("#navsettings").onclick=()=>$("#setmodal").classList.remove("hidden");$("#closes").onclick=()=>$("#setmodal").classList.add("hidden");
$("#addAccount").onclick=()=>{$("#accountName").value="";$("#opening").value=0;fillAccountTypes();$("#accountModal").classList.remove("hidden")};$("#closeAccount").onclick=()=>$("#accountModal").classList.add("hidden");
$("#lang").onchange=e=>{S.lang=e.target.value;save();render()};
$("#form").onsubmit=e=>{e.preventDefault();let n=Number($("#amount").value);if(!n)return;S.tx.push({type,amount:n,cat:$("#cat").value,accountId:$("#account").value,note:$("#note").value.trim(),date:$("#date").value+"T12:00:00"});save();$("#modal").classList.add("hidden");render()};
$("#transferForm").onsubmit=e=>{e.preventDefault();let n=Number($("#transferAmount").value),f=$("#fromAccount").value,t=$("#toAccount").value;if(!n||f==t)return alert(S.lang=="id"?"Pilih dua akun yang berbeda.":"請選擇兩個不同的帳戶。");if(acctBalance(f)<n)return alert(S.lang=="id"?"Saldo akun asal tidak cukup.":"轉出帳戶餘額不足。");S.tx.push({type:"transfer",amount:n,from:f,to:t,note:$("#transferNote").value.trim(),date:$("#transferDate").value+"T12:00:00"});save();$("#transferModal").classList.add("hidden");render()};
$("#accountForm").onsubmit=e=>{e.preventDefault();let n=$("#accountName").value.trim();if(!n)return;S.accounts.push({id:Date.now().toString(),type:$("#accountType").value,name:n,opening:Number($("#opening").value)||0});save();$("#accountModal").classList.add("hidden");render()};
function simple(kind){$("#simple").classList.remove("hidden");$("#simpleTitle").textContent=kind=="goal"?tr("saving"):tr("budget");$("#simpleLabel").textContent=kind=="goal"?tr("simpleGoal"):tr("simpleBudget");$("#simpleInput").value=kind=="goal"?S.goal:S.budget;$("#simpleName").style.display=kind=="goal"?"block":"none";$("#simpleName").value=S.goalName;$("#simpleSave").onclick=()=>{if(kind=="goal"){S.goal=Number($("#simpleInput").value);S.goalName=$("#simpleName").value||"Tabungan"}else S.budget=Number($("#simpleInput").value);save();$("#simple").classList.add("hidden");render()}}
$("#budgetBtn").onclick=()=>simple("budget");$("#goalBtn").onclick=()=>simple("goal");$("#simpleClose").onclick=()=>$("#simple").classList.add("hidden");
$("#clear").onclick=()=>{if(S.tx.length&&confirm(S.lang=="id"?"Hapus semua transaksi?":"刪除全部交易？")){S.tx=[];save();render()}};
$("#export").onclick=()=>{let blob=new Blob([JSON.stringify(S,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="backup-keuangan.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
$("#import").onclick=()=>$("#file").click();$("#file").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.tx||!x.accounts)throw 0;S=x;S.cur="NTD";save();render();alert(S.lang=="id"?"Data berhasil dipulihkan.":"資料還原成功。")}catch{alert(tr("backupInvalid"))}};r.readAsText(f)};
render();
if ("serviceWorker" in navigator) window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));
